### ISSUE TITLE
vm_boot

### ISSUE THREAD

**Issue by LangQingjie** [riscv-software-src/riscv-tests#381]
Hello, I'm using riscv tests to test the rv32-v-add instruction. In the process of generating test code, I use this project, but I find that the space required in the process of generating page table by vmboot is too large. The memory we use is only about 40KB. If we generate page table in this memory size. And can correctly get the program instructions.

**Comment by aswaterman** [comment]
The `v` environment is meant to be used on systems with a reasonably large memory (as practical systems with virtual memory tend to have).  If you only have 40 KiB of memory, you shouldn't run these tests.
