### ISSUE TITLE
unable to build in mac

### ISSUE THREAD

**Issue by quantrpeter** [riscv-software-src/riscv-tests#586]
Hi All
   latest riscv-gnu-toolchain can't work with riscv-tests, unable to build in mac

```
gcc -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

<img width="1522" alt="image" src="https://github.com/user-attachments/assets/d59ebc31-f98e-431f-a914-dc3c192b32f7">

**Comment by TommyMurphyTM1234** [comment]
Any use?

- https://github.com/riscv-software-src/riscv-tests/issues/584

**Comment by quantrpeter** [comment]
Just tried Pull request https://github.com/riscv-software-src/riscv-tests/pull/585, it works, please merge it into main branch :-)

**Comment by TommyMurphyTM1234** [comment]
> Just tried Pull request #585, it works, please merge it into main branch :-)

I don't think that it can based on @aswaterman's comment here: 

- https://github.com/riscv-software-src/riscv-tests/pull/585#pullrequestreview-2379150160
