### ISSUE TITLE
The principle of riscv-tests

### ISSUE THREAD

**Issue by xqx17** [riscv-software-src/riscv-tests#591]
As title,i  just started to learn ,have a bro can explain this problem?

**Comment by libriunk** [comment]
You can refer to [this](https://github.com/lowRISC/riscv-compliance/blob/master/doc/README.adoc)

**Comment by xqx17** [comment]
> You can refer to [this](https://github.com/lowRISC/riscv-compliance/blob/master/doc/README.adoc)

thank you
