### ISSUE TITLE
Question about rv32ui-v tests using `sret` in M-mode

### ISSUE THREAD

**Issue by zhc7** [riscv-software-src/riscv-tests#593]
Hi, I'm new to risc-v. I've noticed that rv32ui-v tests call `vm_boot` at the beginning, and then `vm_boot` calls `pop_tf`. An `sret` instruction appears at the end of `pop_tf`, but the program should still be in M-mode, because there isn't an `mret`, isn't this an illegal instruction? I might have missed something. Really appreciated if anyone can help.

**Comment by aswaterman** [comment]
`sret` is legal in M-mode.  It does the same thing it does in S-mode (it changes the mode to S or U, based upon `sstatus.SPP`).

**Comment by zhc7** [comment]
Thank you for clarifying that!
